# Generated by Django 4.2.6 on 2023-10-14 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Укажите ваш адрес электронной почты', max_length=50, unique=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(help_text='Укажите ваше имя', max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(help_text='Укажите вашу фамилию', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(help_text='Укажите ваш пароль', max_length=50, validators=[django.core.validators.RegexValidator(message='Пароль должен содержать от 5 до 50 символов и может включать буквы, цифры и специальные символы: ~@#$%^&*()_+{}[]:;"<>/?!.\'`-', regex='^[A-Za-zА-Яа-я0-9~@#$%^&*()_+{}\\[\\]:;"<>/?!\\.\\\'`-]{5,40}$')], verbose_name='Пароль'),
        ),
    ]
