# Generated by Django 4.2.6 on 2023-10-14 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Укажите отдел пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customuser', to='users.department', verbose_name='Отдел'),
        ),
    ]
