# Generated by Django 4.2.6 on 2023-10-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Defect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите заголовок",
                        max_length=40,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "body",
                    models.CharField(
                        help_text="Опишите замечание",
                        max_length=100,
                        verbose_name="Замечание",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "low"),
                            ("HIGH", "high"),
                            ("MEDIUM", "medium"),
                        ],
                        default="LOW",
                        help_text="Укажите приоритет замечания",
                        max_length=10,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "new"),
                            ("IN_PROGRESS", "in progress"),
                            ("DONE", "done"),
                        ],
                        default="NEW",
                        help_text="Укажите статус дефекта",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации замечания"
                    ),
                ),
            ],
            options={
                "verbose_name": "замечание",
                "verbose_name_plural": "замечания",
            },
        ),
    ]
