# Generated by Django 4.2.6 on 2023-10-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defect",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "new"),
                    ("IN_PROGRESS", "in progress"),
                    ("DONE", "done"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
    ]
