# Generated by Django 4.2.6 on 2023-10-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0003_alter_defect_options_defect_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="defect",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "low"), ("HIGH", "high"), ("MEDIUM", "medium")],
                default="LOW",
                help_text="Укажите приоритет замечания",
                max_length=10,
                verbose_name="Приоритет",
            ),
        ),
    ]
